# FROM python:3.10

FROM fedora:40

RUN dnf install -y python3 python3-pip
RUN dnf install -y rpm-ostree
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
RUN chmod +x comps-sync.py
WORKDIR /mnt
CMD ["python", "/app/comps-sync.py"]
